### ISSUE TITLE
A server is already running. Check /usr/src/app/tmp/pids/server.pid

### ISSUE THREAD

**Issue by Hareramrai** [coderjourney/03-learn-to-use-docker-in-development#1]
Hi , 

I am getting below error while using you docker configuration. 

````
docker-compose run app 
=> Booting Puma
=> Rails 5.0.0.1 application starting in development on http://0.0.0.0:3000
=> Run `rails server -h` for more startup options
A server is already running. Check /usr/src/app/tmp/pids/server.pid.
Exiting
````

Could you please help me on this. How I can run bash terminal against app container ? 

Thanks,
Hare

**Comment by keiththomps** [comment]
Hi,

Since we defined a CMD in the [Dockerfile](https://github.com/coderjourney/03-learn-to-use-docker-in-development/blob/master/blog/Dockerfile#L14) that will be the default action that is taken when using `docker-compose run app`. If you'd like to instead open up a bash prompt you will need to add the `bash` onto the end. I would also suggest adding the `--rm` flag so that Docker cleans up the container when you exit it:

``` bash
docker-compose run --rm app bash
```

**Comment by Hareramrai** [comment]
Hi @keiththomps 

Thank you for helping me. 

I am having problem to serve the complied assets. 

For that i have added below line to dockerfile. 

```
# Precompile Rails assets
RUN bundle exec rake assets:precompile
```

But  I am not getting any css and js file on browser. 

Also data from postgresql has been lost.  How to make it persistent ? 

Thanks,
Hare

**Comment by keiththomps** [comment]
Your data should be persisted in the volume set up in the docker-compose file. I would make sure that the path is correct for that.

Unless you're running your application in an environment that is set to serve compiled assets, the assets:precompile won't really do much for you. For serving assets, I would suggest you take a look at the tutorial I have for [deploying a rails application](https://www.youtube.com/watch?v=jlVrYgVEl6M). There are better ways to do it, but this is a bare bones way to run a rails application in the production environment.
